# Generated by Django 5.1.7 on 2025-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("close_price", models.FloatField()),
                ("sma20", models.FloatField(blank=True, null=True)),
                ("sma50", models.FloatField(blank=True, null=True)),
                ("macd", models.FloatField(blank=True, null=True)),
                ("signal", models.FloatField(blank=True, null=True)),
                ("rsi", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
