# Generated by Django 5.1.7 on 2025-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_data", "0002_stockdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandlestickPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("signal", models.CharField(max_length=255)),
                ("details_url", models.URLField()),
            ],
        ),
    ]
